### ISSUE TITLE
Creating Contributing.md

### ISSUE THREAD

**Issue by yuvicc** [thefirans/AutoMeet#4]
**This is a(n):**
- [ ] Update to an existing code
- [ ] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
I would like to create a CONTRIBUTING.md file so that newcomers can understand the basic principles of contributing to the repositories and other related information

**Comment by thefirans** [comment]
Create pull request for it, I willreview and merge it👍🏻

**Comment by i-am-yuvi** [comment]
Sure!
